CREATE TABLE IF NOT EXISTS Users
(
    id SERIAL PRIMARY KEY,
    login VARCHAR(60) NOT NULL UNIQUE,
    hashed_password VARCHAR(256) NOT NULL,
    role_id INT REFERENCES Roles(id)
);

CREATE TABLE IF NOT EXISTS Roles
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO Roles (name)
VALUES ('Admin'),
    ('User')
ON CONFLICT DO NOTHING;

