[package]
name = "writer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
clickhouse = { workspace = true }
domain = { workspace = true }
config = { workspace = true }
envy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
tokio-util = { workspace = true }
rdkafka = { workspace = true }
storage = { workspace = true }
postcard = { workspace = true }
service-utils = { workspace = true }