syntax = "proto3";

package log_collector;

import "google/protobuf/timestamp.proto";

service LogCollector {
    rpc SendLogs (stream SignedLogEntry) returns (LogResponse);
}

enum LogLevel {
    INFO = 0;
    WARN = 1;
    ERROR = 2;
}

message LogEntry {
    google.protobuf.Timestamp timestamp = 1;

    LogLevel level = 2;

    string service = 3;

    string message = 4;
}

message SignedLogEntry {
    LogEntry log = 1;

    string service_id = 2;

    int64 signed_at = 3;

    string signature = 4;
}

message LogResponse {
    bool success = 1;

    string error_message = 3;
}